# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaProj.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.label_4.setObjectName("label_4")
        self.leIdUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.leIdUsuario.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.leIdUsuario.setObjectName("leIdUsuario")
        self.leNome = QtWidgets.QLineEdit(self.centralwidget)
        self.leNome.setGeometry(QtCore.QRect(90, 50, 321, 20))
        self.leNome.setObjectName("leNome")
        self.leSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.leSenha.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.leSenha.setObjectName("leSenha")
        self.pbCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pbCadastrar.setEnabled(False)
        self.pbCadastrar.setGeometry(QtCore.QRect(90, 150, 75, 23))
        self.pbCadastrar.setObjectName("pbCadastrar")
        self.pbAtualizar = QtWidgets.QPushButton(self.centralwidget)
        self.pbAtualizar.setEnabled(False)
        self.pbAtualizar.setGeometry(QtCore.QRect(170, 150, 101, 23))
        self.pbAtualizar.setObjectName("pbAtualizar")
        self.pbExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.pbExcluir.setEnabled(False)
        self.pbExcluir.setGeometry(QtCore.QRect(280, 150, 75, 23))
        self.pbExcluir.setObjectName("pbExcluir")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 20, 47, 14))
        self.label_6.setObjectName("label_6")
        self.leBusca = QtWidgets.QLineEdit(self.centralwidget)
        self.leBusca.setGeometry(QtCore.QRect(470, 20, 181, 20))
        self.leBusca.setObjectName("leBusca")
        self.lvUsuarioList = QtWidgets.QListView(self.centralwidget)
        self.lvUsuarioList.setGeometry(QtCore.QRect(430, 50, 221, 192))
        self.lvUsuarioList.setObjectName("lvUsuarioList")
        self.checkAdm = QtWidgets.QRadioButton(self.centralwidget)
        self.checkAdm.setGeometry(QtCore.QRect(90, 110, 91, 21))
        self.checkAdm.setObjectName("checkAdm")
        self.checkUser = QtWidgets.QRadioButton(self.centralwidget)
        self.checkUser.setGeometry(QtCore.QRect(200, 110, 91, 21))
        self.checkUser.setObjectName("checkUser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro de Usuário"))
        self.label.setText(_translate("MainWindow", "Id Usuario:"))
        self.label_2.setText(_translate("MainWindow", "Nome:"))
        self.label_3.setText(_translate("MainWindow", "Senha:"))
        self.label_4.setText(_translate("MainWindow", "Tipo de Conta:"))
        self.pbCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.pbAtualizar.setText(_translate("MainWindow", "Altualizar"))
        self.pbExcluir.setText(_translate("MainWindow", "Excluir"))
        self.label_6.setText(_translate("MainWindow", "Busca"))
        self.checkAdm.setText(_translate("MainWindow", "Administrador"))
        self.checkUser.setText(_translate("MainWindow", "Usuário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
